/* ============================================================
   App assembly — split from index.ts so tests can build the
   full HTTP app against an embedded database with app.inject().

   When STATIC_DIR is set (production), the server also serves the
   built frontend from that directory — one origin for app + API,
   so session cookies work with no CORS configuration.
   ============================================================ */
import Fastify, { type FastifyInstance } from "fastify";
import cookie from "@fastify/cookie";
import rawBody from "fastify-raw-body";
import fastifyStatic from "@fastify/static";
import { existsSync } from "node:fs";
import path from "node:path";
import type { Db } from "./db/index.js";
import { registerAuthRoutes } from "./routes/auth.js";
import { registerStaffRoutes } from "./routes/staff.js";
import { registerTenantRoutes } from "./routes/tenant.js";
import { registerTenantStateRoutes } from "./routes/tenantState.js";
import { registerAdminRoutes, isPlatformAdmin } from "./routes/admin.js";
import { registerPublicOnboardingRoutes } from "./routes/onboarding-public.js";
import { registerPublicSiteRoutes } from "./routes/public-site.js";
import { registerSignupRoutes } from "./routes/signup.js";
import { registerEnquiryRoutes } from "./routes/enquiries.js";
import { registerEarlyAccessRoutes } from "./routes/early-access.js";
import { registerPinRoutes } from "./routes/pin.js";
import { registerRatesRoutes } from "./routes/rates.js";
import { registerLedgerRoutes } from "./ledger/routes.js";
import { refreshSiteDomains, registerSiteRoutes, rewriteHostToSite } from "./sites.js";
import { registerQuoteRoutes } from "./quotes/routes.js";
import { registerBillingRoutes } from "./routes/billing.js";

/* Standalone pages of the marketing site, beyond the front door. Each is
   generated by scripts/build-site.mjs from a design in design/site/ and is
   served only once that design exists — until then the site's links point at
   the matching section of the front page instead. */
const SITE_PAGES = {
  "/legal": "web/legal.html",
  "/faq": "web/faq.html",
  "/compliance": "web/compliance.html",
  "/contact": "web/contact.html",
  "/add-ons": "web/add-ons.html",
  // the Early Access application — what every "Get early access" on the site
  // leads to. Applying is not the same as opening a desk: an accepted
  // operator creates theirs from the OS's own wizard, at /app?signup=1.
  "/signup": "web/early-access.html",
  // where the invite email lands: type your code, walk the setup
  "/onboarding": "web/onboarding.html",
} as const satisfies Record<string, string>;

/* Phones and small tablets get the phone design. Deliberately coarse: the
   cost of a wrong guess is a layout the visitor can still read and correct
   with /d, so it errs toward the desktop page. */
const isPhone = (ua: string | undefined): boolean =>
  !!ua && /iphone|ipod|android.*mobile|windows phone|blackberry|iemobile|opera mini/i.test(ua);

/* STATIC_DIR is the repository root in the Render deployment so the prototype,
   marketing site, and hosted storefront can share one process. Never expose
   that root wholesale: it also contains server source, deployment config,
   Git metadata, and local environment files. Keep the static plugin on a
   small, explicit allow-list; route handlers below still serve the app shells
   with reply.sendFile. */
const isPublicAsset = (pathname: string): boolean => {
  // Wildcard requests arrive with a leading slash; reply.sendFile receives a
  // relative file path. Apply the same boundary to both paths.
  const file = pathname.startsWith("/") ? pathname : `/${pathname}`;
  return (
    file === "/CurrencyDesk OS.html" ||
    file === "/frontend.html" ||
    file === "/admin.html" ||
    file === "/yorkfx.css" ||
    file === "/yorkfx-converter.js" ||
    file.startsWith("/assets/") ||
    file.startsWith("/os-src/") ||
    /* The Rate Board, which the OS embeds in an iframe, and the storefront
       pages beside it. Public design content — no server source, no config.
       Without this the iframe asks for a file the static handler refuses and
       lands on the not-found path below, which used to answer with the
       marketing site: the OS showed "More trades. Less paperwork." where the
       rate board should be. */
    file.startsWith("/YorkFX/") ||
    file.startsWith("/web/")
  );
};

/* Is this request a page, or something a page asked for?

   It matters because the fallback below answers with the site's front page,
   which is right for a deep link somebody typed and catastrophic for
   anything else: a mistyped script path came back 200 with HTML in it, an
   iframe whose source was missing rendered the marketing site inside the
   product, and neither looked like an error anywhere.

   Sec-Fetch-Dest says exactly which it is — "document" only for a top-level
   navigation, "iframe"/"script"/"style"/"image" for everything a page pulls
   in. Browsers that do not send it fall back to Accept, the older and
   coarser version of the same question.

   A caller that sends neither gets the page. That is not a guess worth
   tightening: every browser sends at least Accept, so what is left is
   tooling and health checks, and the permissive answer is what this route
   has always given them. */
const wantsPage = (req: { headers: Record<string, unknown> }): boolean => {
  const dest = req.headers["sec-fetch-dest"];
  if (typeof dest === "string") return dest === "document";
  const accept = req.headers.accept;
  if (typeof accept !== "string" || accept === "") return true;
  return accept.includes("text/html");
};

export async function buildApp(db: Db): Promise<FastifyInstance> {
  const app = Fastify({
    logger: process.env.NODE_ENV !== "test",
    // a customer domain pointed at us serves that customer's hosted site
    rewriteUrl: (req) => rewriteHostToSite(req.headers.host, req.url ?? "/"),
  });
  await app.register(cookie);
  await app.register(rawBody, { global: false, encoding: false, runFirst: true });
  await refreshSiteDomains(db);

  app.get("/api/health", async () => ({ ok: true, service: "currencydesk-server" }));
  registerAuthRoutes(app, db);
  registerSignupRoutes(app, db);
  registerEnquiryRoutes(app, db);
  registerEarlyAccessRoutes(app, db);
  registerPinRoutes(app, db);
  registerStaffRoutes(app, db);
  registerTenantRoutes(app, db);
  registerTenantStateRoutes(app, db);
  registerAdminRoutes(app, db);
  /* There used to be a second, staff-side copy of the whole setup flow —
     sixteen steps an operator could fill in on somebody's behalf. It is
     gone. Setting a desk up is the customer's job on the link we email
     them, and a parallel implementation of the same flow was two things
     to keep in step for the sake of a screen nobody wanted to work. */
  registerPublicOnboardingRoutes(app, db);
  registerPublicSiteRoutes(app, db);
  registerRatesRoutes(app, db);
  registerBillingRoutes(app, db);
  const ledgerDatabaseUrl = process.env.LEDGER_DATABASE_URL ?? process.env.DATABASE_URL;
  if (ledgerDatabaseUrl) {
    registerLedgerRoutes(app, db, ledgerDatabaseUrl);
    registerQuoteRoutes(app, db, ledgerDatabaseUrl);
  }

  // serve the built frontend (vite build → dist) when configured
  const staticDir = process.env.STATIC_DIR ? path.resolve(process.env.STATIC_DIR) : null;
  if (staticDir && existsSync(staticDir)) {
    // which HTML is the app shell:
    //   production (Render): STATIC_DIR=../dist → frontend.html (vite build)
    //   prototype mode (npm run dev:prototype): STATIC_DIR=.. STATIC_INDEX="CurrencyDesk OS.html"
    const indexFile = process.env.STATIC_INDEX ?? "frontend.html";
    // the public front door. When SITE_INDEX is present in the static dir the
    // marketing site serves at "/" and the OS moves to "/app"; without it the
    // OS keeps the root, so a deploy that ships only the app still works.
    const siteFile = process.env.SITE_INDEX ?? "web/index.html";
    const hasSite = existsSync(path.join(staticDir, siteFile));
    const rootFile = hasSite ? siteFile : indexFile;
    // the marketing site is two designs, not one responsive page: the desktop
    // layout has no mobile breakpoints, and the phone layout is its own
    // document. Serve whichever the visitor can actually read.
    const mobileFile = process.env.SITE_MOBILE_INDEX ?? "web/mobile.html";
    const hasMobile = hasSite && existsSync(path.join(staticDir, mobileFile));

    await registerSiteRoutes(app, staticDir);
    await app.register(fastifyStatic, {
      root: staticDir,
      index: false,
      dotfiles: "deny",
      // Hosted storefront routes pass their own dedicated root to sendFile;
      // this guard applies only to requests served from the repository root.
      allowedPath: (pathname, root) => root !== staticDir || isPublicAsset(pathname),
    });
    app.get("/", (req, reply) => {
      if (!hasMobile) return reply.sendFile(rootFile);
      // caches must not serve one layout to the other audience
      reply.header("Vary", "User-Agent");
      return reply.sendFile(isPhone(req.headers["user-agent"]) ? mobileFile : rootFile);
    });
    if (hasSite) {
      // the OS itself. Assets load with paths relative to the root, so every
      // route that serves it must be a single path segment — deep links
      // collapse back onto "/app". "/signup" is the OS's own new-desk wizard
      // only while the design's Early Access page is missing; once that page
      // is built it owns the route (see SITE_PAGES).
      const productRoutes = ["/app", "/login"];
      if (!existsSync(path.join(staticDir, SITE_PAGES["/signup"]))) productRoutes.push("/signup");
      for (const route of productRoutes) {
        app.get(route, (_req, reply) => reply.sendFile(indexFile));
      }
      app.get("/app/", (_req, reply) => reply.redirect("/app", 301));
      app.get("/app/*", (_req, reply) => reply.redirect("/app", 301));
      // both layouts, addressable directly — /m for the phone design, /d to
      // override a wrong guess about the visitor's device
      if (hasMobile) app.get("/m", (_req, reply) => reply.sendFile(mobileFile));
      app.get("/d", (_req, reply) => reply.sendFile(rootFile));
      for (const [route, file] of Object.entries(SITE_PAGES)) {
        if (existsSync(path.join(staticDir, file))) {
          app.get(route, (_req, reply) => reply.sendFile(file));
        }
      }
      /* The invite link reads like an address rather than a query string:
         currencydeskos.com/onboarding/CD-A3V5ZE. The page pulls the code off
         the path itself, so every one of these serves the same file. */
      if (existsSync(path.join(staticDir, SITE_PAGES["/onboarding"]))) {
        app.get("/onboarding/:code", (_req, reply) => reply.sendFile(SITE_PAGES["/onboarding"]));
      }
    }
    // the platform control panel — served whether prod ships the vite build or
    // the prototype, as long as admin.html is in the static dir (repo root)
    if (existsSync(path.join(staticDir, "admin.html"))) {
      app.get("/admin", (_req, reply) => reply.sendFile("admin.html"));
    }
    app.setNotFoundHandler((req, reply) => {
      /* Only a page gets a page. A missing script, stylesheet, image or
         iframe source is a 404 — saying otherwise hands the caller HTML
         where it expected code and turns a one-line mistake into an hour of
         wondering why the product is showing the marketing site. */
      if (req.method === "GET" && !req.url.startsWith("/api/") && wantsPage(req)) {
        // unknown paths under /app belong to the OS; everything else lands on
        // the public site (or the OS, when no site is deployed)
        if (req.url.startsWith("/app")) return reply.sendFile(indexFile);
        if (!hasMobile) return reply.sendFile(rootFile);
        reply.header("Vary", "User-Agent");
        return reply.sendFile(isPhone(req.headers["user-agent"]) ? mobileFile : rootFile);
      }
      return reply.code(404).send({ error: "not_found" });
    });
  }

  return app;
}
