import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import pg from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import type { FastifyInstance } from "fastify";
import { createDb, schema, type DbHandle } from "../src/db/index.js";
import { DEMO, seed } from "../src/seed.js";
import { buildApp } from "../src/app.js";

const url = process.env.TEST_DATABASE_URL;
const postgres = url ? describe : describe.skip;
let pool: pg.Pool; let app: FastifyInstance; let handle: DbHandle;
const post = { idempotencyKey:"route-post", customerId:"customer-demo", from:"CAD", to:"USD", inputAmount:"1000.00", feeCad:"4.00", purpose:"Travel", sourceOfFunds:"Cash" };
const cookie = async (staffId="a.singh") => { const login=await app.inject({method:"POST",url:"/api/auth/login",payload:{staffId,password:DEMO.password}}); return { cdos_session: login.cookies.find((item)=>item.name==="cdos_session")!.value }; };
async function resetLedger() { await pool.query("TRUNCATE ledger_audit_events,ledger_reversal_entries,ledger_reversals,ledger_till_movements,ledger_journal_entries,ledger_transactions,ledger_idempotency,ledger_till_balances,ledger_rates,ledger_customers,ledger_principals CASCADE"); const s=[DEMO.tenantId,DEMO.legalEntityId,DEMO.branchId,DEMO.workspaceId,"till-01"]; await pool.query("INSERT INTO ledger_principals VALUES ($1||':a.singh',$1,$2,$3,$4,$5,'teller','[\"br-yorkville\"]'),($1||':r.haddad',$1,$2,$3,$4,$5,'branch_manager','[\"br-yorkville\"]')",s); await pool.query("INSERT INTO ledger_customers VALUES ('customer-demo',$1,$2,$3,$4,'Demo Customer','Normal','verified')",s.slice(0,4)); await pool.query("INSERT INTO ledger_rates VALUES ($1,$2,$3,$4,'CAD',1),($1,$2,$3,$4,'USD',0.731),($1,$2,$3,$4,'EUR',0.676),($1,$2,$3,$4,'GBP',0.581)",s.slice(0,4)); for(const [currency,value] of [["CAD",25000],["USD",12000],["EUR",7000],["GBP",3500]])await pool.query("INSERT INTO ledger_till_balances VALUES ($1,$2,$3,$4,$5,$6,$7)",[...s,currency,value]); }
postgres("ledger HTTP routes against real PostgreSQL",()=>{ beforeAll(async()=>{process.env.PGLITE_MEMORY="1";process.env.LEDGER_DATABASE_URL=url;pool=new pg.Pool({connectionString:url});await pool.query(await readFile(resolve(process.cwd(),"src/ledger/migration.sql"),"utf8"));handle=await createDb();await seed(handle.db);app=await buildApp(handle.db);});afterAll(async()=>{await app.close();await handle.close();await pool.end();delete process.env.LEDGER_DATABASE_URL;});beforeEach(resetLedger);
  it("posts and deduplicates through HTTP",async()=>{const c=await cookie();const a=await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,payload:post});const b=await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,payload:post});expect(a.statusCode).toBe(201);expect(b.json().transactionId).toBe(a.json().transactionId);expect((await pool.query("SELECT count(*) FROM ledger_transactions")).rows[0].count).toBe("1");});
  it("returns 401 without session, 403 for invalid workspace, wrong branch, or database role",async()=>{expect((await app.inject({method:"POST",url:"/api/ledger/exchanges",payload:post})).statusCode).toBe(401);const c=await cookie();expect((await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,headers:{"x-workspace-id":"missing"},payload:{...post,idempotencyKey:"scope"}})).statusCode).toBe(403);await handle.db.insert(schema.branches).values({id:"br-other",tenantId:DEMO.tenantId,legalEntityId:DEMO.legalEntityId,name:"Other branch"});await handle.db.insert(schema.workspaces).values({id:"workspace-other",tenantId:DEMO.tenantId,legalEntityId:DEMO.legalEntityId,branchId:"br-other",tillId:"till-other"});expect((await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,headers:{"x-workspace-id":"workspace-other"},payload:{...post,idempotencyKey:"wrong-branch"}})).statusCode).toBe(403);await pool.query("UPDATE ledger_principals SET role='auditor' WHERE user_id=$1",[`${DEMO.tenantId}:a.singh`]);expect((await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,payload:{...post,idempotencyKey:"role"}})).statusCode).toBe(403);});
  it("rejects malformed request and maps unexpected database failure to 500",async()=>{const c=await cookie();expect((await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,payload:{...post,inputAmount:"1e3"}})).statusCode).toBe(400);await pool.query("ALTER TABLE ledger_principals RENAME TO ledger_principals_broken");try { const response=await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:c,payload:{...post,idempotencyKey:"internal"}});expect(response.statusCode).toBe(500);expect(response.json().code).toBe("INTERNAL_ERROR"); } finally { await pool.query("ALTER TABLE ledger_principals_broken RENAME TO ledger_principals"); }});
  it("reverses through HTTP and rejects a second reversal",async()=>{const teller=await cookie();const tx=(await app.inject({method:"POST",url:"/api/ledger/exchanges",cookies:teller,payload:post})).json().transactionId;const manager=await cookie("r.haddad");expect((await app.inject({method:"POST",url:`/api/ledger/transactions/${tx}/reversal`,cookies:manager,payload:{idempotencyKey:"reverse",reason:"Correction"}})).statusCode).toBe(201);expect((await app.inject({method:"POST",url:`/api/ledger/transactions/${tx}/reversal`,cookies:manager,payload:{idempotencyKey:"reverse-2",reason:"Again"}})).statusCode).toBe(422);});
});
